# Generated by Django 4.2.25 on 2025-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_add_spatial_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='source_ref',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
